Add cli options to snippets script

diff --git a/scripts/snippets b/scripts/snippets
--- a/scripts/snippets
+++ b/scripts/snippets
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-if [ "$1" == "backup" ]
+if [[ "$1" == "export" ]]
 then
 	if ! [[ -e ~/.local/share/snippet-box ]]
 	then
@@ -9,10 +9,35 @@ then
 	fi
 
 	cp ~/.local/share/snippet-box/db.sqlite3 .
-	tar -czvf snippets_data.tar.gz db.sqlite3
+	tar -czf snippets_data.tar.gz db.sqlite3
 	rm db.sqlite3
 
+	echo "Export success"
+
 	exit 0
+fi
+
+
+if [[ "$1" == "import" ]] && [[ $# -eq 2 ]]
+then
+	folder=$(mktemp -d)
+	cp "$2" "$folder"
+	cd "$folder"
+	if tar -xf "${2}"
+	then
+		sudo mv db.sqlite3  ~/.local/share/snippet-box/db.sqlite3
+	else
+		echo "Unable to extract."
+		exit 1
+	fi
+
+	echo "Import success. Make sure to restart docker container for changes to take effect."
+
+	exit 0
+elif [[ "$1" == "import" ]]
+then
+	echo "Missing file."
+	exit 1
 fi
 
 if ! [[ -e ~/bin/snippet-box ]]
@@ -25,7 +50,7 @@ fi
 
 if which docker > /dev/null 2>&1
 then
-	docker run --rm -p 5000:5000 -v ~/.local/share/snippet-box:/app/data snippet-box
+	docker run --rm -d -p 5000:5000 -v ~/.local/share/snippet-box:/app/data snippet-box
 else
 	echo "Docker is not installed."
 fi
